### ISSUE TITLE
No function stft() in mix_signals.m

### ISSUE THREAD

**Issue by Joseph-sun** [ehabets/ANF-Generator#2]
In mix_signals.m 66 lines, seems the "stft" function doesn't exist in my matlab?
And in mix_signals.m 88 lines, "istft" function also doesn't exist
Would you mind helping me how to find them?

**Comment by ehabets** [comment]
The function "stft" was introduced in MATLAB 2019a (see: https://de.mathworks.com/help/signal/ref/stft.html). If you are unable to upgrade to a newer MATLAB version, you can instead use an open source implementation (e.g., https://israelcohen.com/software/).
