### ISSUE TITLE
How to compute inter-mic distance for general mic arrays and cylindrical noise

### ISSUE THREAD

**Issue by fakufaku** [ehabets/ANF-Generator#3]
Hi @ehabets , thank you for sharing this code! I am implementing the method for general arrays to integrate in [pyroomacoustics](https://github.com/LCAV/pyroomacoustics), and I have a couple of question about cylindrical noise.

1. The papers and the code are not completely clear about how the distance `d` between two sensors should be interpreted for general arrays in 3D. If the cylinder axis is the `z`-axis, is it correct to take `d` as the horizontal distance `sqrt(x ** 2 + y ** 2)` ?
2. While inspecting the code, I saw that you recommend to use Cholesky rather than eigenvalue decomposition for babble noise. What is the rational for that ?

Thank you in advance for your help!

**Comment by ehabets** [comment]
Thank you for your inquiry, @fakufaku.

1. For a 3D array, you indeed need to take the Euclidian distance between the sensor positions.
2. The EVD produces eigenvectors that can largely vary from one frequency band to the following. This can lead to discontinuities in the filters’ magnitude response. The Cholesky decomposition was found to produce "smoother" magnitude responses and, consequently, more natural-sounding babble noise. A discussion and some improvements are discussed in [1].

[1] https://doi.org/10.1121/10.0003565

**Comment by fakufaku** [comment]
Thanks for the quick replay! Just to confirm:
1. For spherical noise, we use the sinc function and the 3D euclidean distance. For cylindrical noise, we use the Bessel function and the _horizontal_ distance between sensors (i.e., ignoring z). Is that correct ?
2. I see, interesting! Thank you for the additional reference!

**Comment by ehabets** [comment]
1. Correct. Please note that these models hold only for omnidirectional sensors in free-field.
2. You're welcome.

**Comment by fakufaku** [comment]
> Please note that these models hold only for omnidirectional sensors in free-field.

Excellent point, I need to add an error or warning if directional microphones are used! 👍 
Thank you so much for your help! 🙏

**Comment by fakufaku** [comment]
Here is where I started to add the code in case you are interested!
https://github.com/LCAV/pyroomacoustics/pull/296
