### ISSUE TITLE
question about stft function

### ISSUE THREAD

**Issue by fromprimary** [ehabets/ANF-Generator#4]
When I ran gen_babble_speech.m, there was an error. no stft function . My matlab version is R2016a, Signal Processing Toolbox version is 7.2. which version is your matlab?

**Comment by ehabets** [comment]
The [stft function](https://www.mathworks.com/help/signal/ref/stft.html) was introduced in MATLAB version R2019a.

Commit [1a5f1a1](https://github.com/ehabets/ANF-Generator/commit/1a5f1a14144956419e4ddb79193cc7accee40786) contains the stft and istft functions.
